#!/bin/bash

# Copyright (C) 2006-2016 Amazon.com, Inc. or its affiliates.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#    http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the
# License.

#Expected input if partition's kernel name like nvme0n1p2
if [ $# -eq 0 ] ; then
  exit 1
else
  # extract ns id from partition's kernel name and export it
  NSID=$(echo -n "$@" | cut -f 3 -d 'n' | cut -f 1 -d 'p')
  echo "_NS_ID=${NSID}"
fi
